mozilla_django_oidc/auth.py, mozilla_django_oidc/utils.py, runtests.py, tests/test_auth.py
* Use a default username algo.
* Allow users to override the algo through settings.
=> Handle user creation.

mozilla_django_oidc/urls.py
* Use string to define module path instead of class instance
=> Fix overriding callback class.

mozilla_django_oidc/contrib/auth0/utils.py
=> Fix typo in auth0 signout.

docs/installation.rst
=> Add documentation for connecting oidc identities to django users

docs/installation.rst, mozilla_django_oidc/auth.py, tests/test_auth.py
* fix default_username_algo to return the correct types and add tests
* add docs regarding how mozilla-django-oidc generates Django User accounts and
how to change how usernames are generated
Fixes #91.
=> Clean up username generation and document it

docs/installation.rst
Add a Jinja2 example.
Fixes #97.
=> Add Jinja2 example

docs/installation.rst
* add section on getting a client id and secret
* note that you need a client id and secret for every environment you're using
* break up settings changes so it's clearer what comes from where
* add warning about client id and secret being secret
=> Re-organize installation to clarify things

CONTRIBUTING.rst
=> Update docs for running tests

docs/installation.rst
* fix the client id and secret settings
* fix the jinja2 template example
=> Fix docs errors

docs/installation.rst, docs/settings.rst
=> Fix docs related to LOGOUT_REDIRECT_URL

mozilla_django_oidc/views.py, tests/test_views.py
=> always redirect to logout_url even when logged out, fixes #121

docs/installation.rst, setup.py, tox.ini
=> Drop support for Django 1.9

mozilla_django_oidc/contrib/auth0/middleware.py, mozilla_django_oidc/utils.py, mozilla_django_oidc/views.py
Sorry. Just now when preparing this PR I noticed you had assigned the issue to yourself @johngian 
I hope you haven't put to much work into a patch already.
=> django 1.10 and user.is_authenticated, fixes #125

mozilla_django_oidc/middleware.py
=> remove logout_url function, fixes #109

mozilla_django_oidc/views.py, tests/test_views.py
This uses Django's is_safe_url to sanitize the next url for the authentication
view. This prevents open redirects
=> Sanitizes next url for authentication view

HISTORY.rst, README.rst
* adds security notations to HISTORY which we should continue going forward
* updates release process by adding how to handle security issues and indicators
of severity
=> Improve security notations in HISTORY

HISTORY.rst
Followup on https://github.com/mozilla/mozilla-django-oidc/pull/165#issuecomment-327803652
=> update history with @GermanoGuerrini's change

HISTORY.rst
r? anybody?
Just looks like we're too used to writing Markdown :)
=> history restructured text fixes

docs/settings.rst, mozilla_django_oidc/auth.py
Fixes #149
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>
=> Implement RS256 verification

README.rst
This PR changes the build badges to SVG for sharper readability ✨
=> README: Use SVG build badges

mozilla_django_oidc/views.py, tests/test_views.py
New PR to include test case for mozilla/mozilla-django-oidc#195 by @GermanoGuerrini.
@peterbe let me know if you need me to rebase / squash (just didn't want to lose @GermanoGuerrini's authorship)
=> Logout url method request

.gitignore, CONTRIBUTING.rst, Makefile, docs/conf.py, docs/index.rst, docs/installation.rst
* Fix warnings in documentation build.
=> Add test settings in Sphinx conf.

HISTORY.rst, docs/installation.rst, docs/settings.rst
=> Add documentation around OIDC_OP_LOGOUT_URL_METHOD. Fixes #217.

HISTORY.rst, docs/settings.rst, mozilla_django_oidc/auth.py, mozilla_django_oidc/views.py, tests/namespaced_urls.py, tests/test_auth.py, tests/test_views.py
=> Allow namespaced authentication_callback_url

HISTORY.rst, mozilla_django_oidc/auth.py
Fixes #149, #178
Just introduced some methods to easily extend the `mozilla_django_oidc.auth.OIDCAuthenticationBackend`
=> Refactor auth backend

setup.py
* Remove conditional support for cryptography 1.9
* Change project development status
=> Setup script maintenance.

mozilla_django_oidc/middleware.py, mozilla_django_oidc/utils.py, mozilla_django_oidc/views.py, tests/test_middleware.py, tests/test_utils.py, tests/test_views.py
This is a follow up on #345 and #358 . @jwhitlock / @johngian quick r?
=> Move nonce outside of add_state_and_noce_to_session method.

docs/settings.rst, mozilla_django_oidc/auth.py
Co-authored-by: Christian Franke <nobody@nowhere.ws>
=> fix(auth): merge suggestion of @cfra to prevent KeyError in auth.py

CONTRIBUTING.rst, docs/installation.rst, mozilla_django_oidc/auth.py, setup.py, tests/test_auth.py
=> Cleanup references of Python2

mozilla_django_oidc/views.py
=> Update views.py (fix comment)

HISTORY.rst, docs/installation.rst, mozilla_django_oidc/auth.py, tests/test_auth.py
* Add tests for ES256
* Mention ES256 in the documentation
* Add comments in tests
=> Add support for Elliptic Curve signing algorithm

mozilla_django_oidc/middleware.py, tests/test_middleware.py
This PR addresses https://github.com/mozilla/mozilla-django-oidc/issues/397#issuecomment-1432588711.
=> add PKCE to SessionRefresh middleware
