mozilla_django_oidc/contrib/auth0/utils.py, mozilla_django_oidc/views.py, tests/auth0_tests/test_utils.py, tests/test_views.py
* Support post http method on logout.
=> Logout user from OP.

CONTRIBUTING.rst, README.rst, docs/settings.rst
This cleans up some Sphinx/reST formatting in the docs.
Seems like PyPI is displaying the long description correctly, but I've definitely seen it have issues with improperly formatted headers. This fixes those.
This adds url syntax around urls. While urls do get picked up and linkified, adding the url syntax makes it unlikely for the url link to pick up stray characters that are part of a sentence or something else.
"attribute" isn't a valid directive, but "py:attribute::" is and I'm pretty sure it's indexed, too.
Mostly this is cosmetic and doesn't change the meaning of anything.
=> Fix formatting issues in docs

.travis.yml, requirements/requirements.txt, requirements/requirements_dev.txt, requirements/requirements_test.txt, setup.py, tox.ini
* add test environments covering Django 1.11 and Python 3.6
* fix tox environments so they test correctly
* remove requirements.txt which is an out-of-sync copy of what's in setup.py
Fixes #85.
=> Add support for Django 1.11 and Python 3.6

mozilla_django_oidc/auth.py, tests/test_auth.py
* Return `None` if request not available in kwargs
=> Allow combining OIDCAuthenticationBackend with other backends.

docs/installation.rst
The docs were missing two additional things you had to have in your settings.
This adds them.
=> Fix middleware docs

mozilla_django_oidc/auth.py, tests/test_auth.py
@willkg I couldn't add you as a reviewer. 
Once we land this we should make a release since it's blocking any usage in Python 3.5.
=> always decode verified token before json.load(), fixes #116

docs/installation.rst
This fixes the user creation docs so it's easier to skim to find what you're
looking for. It also adds a blurb on OIDC_CREATE_USER setting. It also fixes
a bug in the create_user example.
Fixes #96
=> Document OIDC_CREATE_USER and fix optional user creation docs

mozilla_django_oidc/auth.py, tests/test_auth.py
Emails aren't case sensitive, so we need to match the email address in the claim
with a Django user using a case-insensitive match.
This is part of issue #102.
=> Change email matching to be case-insensitive

docs/installation.rst, docs/settings.rst, mozilla_django_oidc/auth.py, mozilla_django_oidc/middleware.py, mozilla_django_oidc/utils.py, mozilla_django_oidc/views.py, tests/settings.py, tests/test_auth.py, tests/test_middleware.py, tests/test_utils.py, tests/test_views.py
If we don't *really* need to be able to create absolute URLs in "offline" mode, then I think it's much more convenient to use the `request` to generate absolute URLs in runtime.
=> use request instead of SITE_URL, fixes #136

README.rst, mozilla_django_oidc/auth.py, mozilla_django_oidc/middleware.py, mozilla_django_oidc/views.py, setup.py, tests/test_auth.py, tests/test_middleware.py, tests/test_views.py
It occurred to me that `django.utils.encoding.smart_bytes` works all the way back in Django 1.8.
Also, I changed the `ImportError` tricks to always try Python 3 first.
=> [refactoring] smart_bytes exists in django 1.8

docs/index.rst, docs/installation.rst, setup.py
This adds the trove classifiers for OSX and Linux, but not Windows.
This adds a note to the installation chapter about supported Python versions and
platforms.
Does this look ok? I wondered whether to be explicit and say "We don't support Windows." or not. Would that be a better thing to have in the installation chapter?
=> Add note about platform support

docs/settings.rst, mozilla_django_oidc/middleware.py, mozilla_django_oidc/views.py, tests/test_middleware.py, tests/test_views.py
This patch makes the requested set of OpenID Connect scopes configurable, but
defaults to "openid email".
The "email" scope was never requested, which means that any privacy-sensitive
IdP would not send the users' email address.
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>
=> Request the correct OpenIDC scopes

tests/test_utils.py
Adds a check to ensure absolutify cannot be tricked into going to an alternate address.
=> Add path host injection unit-test

docs/settings.rst, mozilla_django_oidc/auth.py, tests/test_auth.py
* Fix name issue with ``OIDC_STORE_ID_TOKEN`` (was ``OIDC_STORE_ACCESS_TOKEN``)
* Implement functionality to store ``access_token`` in user session and add
config entry to control this feature
=> Revisit OIDC_STORE_{ACCESS,ID}_TOKEN config entries

docs/settings.rst, mozilla_django_oidc/views.py, tests/test_views.py
The audience parameter is included in the `aud` claim in the resulting
tokens, and can allow other RPs to authenticate the tokens as well.
=> Allow configuration of additional auth parameters

mozilla_django_oidc/auth.py, setup.py, tests/test_auth.py
This adopts [josepy](https://github.com/jezdez/josepy) (formerly [acme.jose](https://github.com/certbot/certbot/tree/7c1115881012d62c9903c60a0fd57023b641b8d4/acme/acme/jose)) for the JOSE verification.
It also adds a bit of shim since the python-jose did a bit more in terms of verification, but that seems little compared to what we gain security wise.
I think it would make sense to try this out on a real website that uses this, as of now I don't have access to one myself.
Any helpers?
=> Switch to using josepy. Fix #180.

mozilla_django_oidc/auth.py, tests/test_auth.py
CC @jezdez @willkg 
With this fix, I can use mozilla-django-oidc 0.4.0 in my Python 3.6 project.
=> send bytes to josepy, fixes #189

mozilla_django_oidc/auth.py, tests/test_auth.py
For the record, I was following the installation instructions here: https://github.com/mozilla/mozilla-django-oidc/blob/b0e7f075c3668b9d6118165e04bcb8ca120c8cfa/docs/installation.rst#generating-usernames
=> Fix OIDC_USERNAME_ALGO to actually load dotted import path of callback.

mozilla_django_oidc/middleware.py, tests/test_middleware.py
One thing that hurt my eye when I looked through the code is that we compute a list of URLs on every single request. Even when the list is never even used. 
It's pretty much CPU-bound so it wasn't horribly slow but it hurt to see it go to waste.
This PR makes the computation of all `exempt_urls` a once-per-processor thing. 
It also changes to a set which is faster to look for an item in. 
Lastly it rearranges the order so the comparison of `request.path` with the exempt URLs happens last.
=> used cached_property on exempt_urls

mozilla_django_oidc/views.py, tests/test_middleware.py
I admit that I did this quite hastily. But the principle is sound. If the callback is unhappy with the client, the client shouldn't be allowed to stay logged in. Not just in principle but because if you're allowed to stay logged in, when you reach the login_failure URL (whatever that is) the middleware might think it's time to refresh your session and you get swept up in a loop.
=> Log out when session refresh fails

docs/settings.rst, mozilla_django_oidc/urls.py, mozilla_django_oidc/views.py, tests/test_views.py
I am using Auth0 and need a way to pass the `?connection=` parameter to hint to Auth0 which Identity Provider to use (of which there will be multiple).  
`OIDC_AUTH_REQUEST_EXTRA_PARAMS` would work if I only had one connection option, but I need to dynamically decide which connection param I want to use in the extra params.
Therefore, I have implemented two hooks to allow this behavior:
* `OIDCAuthenticationRequestView.get_extra_params` provides the `OIDC_AUTH_REQUEST_EXTRA_PARAMS`, but allows a subclass to override and dynamically change based upon the `request`
* `OIDC_AUTHENTICATE_CLASS` (modeled after `OIDC_CALLBACK_CLASS`) to allow registering a custom subclass as the view to use for the url.  I debated the naming on this, but picked it to match the `/authenticate/` URL, so as to …
=> get_extra_params and OIDC_AUTHENTICATE_CLASS

mozilla_django_oidc/auth.py, tests/test_auth.py
In order for the OIDCAuthenticationBackend to be combined with other auth
backends it needs to return `None` when the call arguments are not targeting
this specific backend. This way we allow Django to try the next available
backend defined in settings.
=> Return `None` when authenticate() request has no `state` or `code`

docs/drf.rst, docs/index.rst, mozilla_django_oidc/auth.py, mozilla_django_oidc/contrib/drf.py, mozilla_django_oidc/utils.py, tests/test_contrib_drf.py, tox.ini
Related issue: https://github.com/mozilla/mozilla-django-oidc/issues/227
Mostly this involves refactoring the part that transforms a request (specifically its `Authorization` header) into a user object, so that there's a method you can use for *only* retrieving the user, which can then be re-used in the stateless/session-less DRF authentication class.
While working on this I found some minor issues which I extraced into smaller individual PRs. This PR depends on these, and I will rebase this PR when/if those are merged:
=> implement authentication class for DRF

mozilla_django_oidc/auth.py, tests/test_auth.py
Previously it could occur that during authentication a user would try to be created without the email claim. However the create_user function would now allow for this, returning `None`. However on the surface everything seems to work fine, with no debug or warning messages to speak of. Instead of always returning `True` for `verify_claims` it would therefor make more sense if this function actually checked if the email is present before trying to create the user.
If this would break existing functionality perhaps some explicit warning message should be logged when the `create_user` function would not create the user and return `None` to prevent hours of debugging for people :)
=> Verify email is in claims before creating user

mozilla_django_oidc/middleware.py, mozilla_django_oidc/views.py
* Remove middleware mixin compatibility for Django < 1.10
* Remove compatibility code for is_safe_url signature < 1.11
=> Remove compatibility code for unsupported Django versions.

docs/drf.rst
There is a typo to an unresolved class on DRF docs, this changes that to point to auth module
=> docs(DRF): Fix OIDC_DRF_AUTH_BACKEND reference

mozilla_django_oidc/middleware.py
There is a `settings.OIDC_AUTHENTICATION_CALLBACK_URL` which is obeyed in `auth.py`. This makes it uniform and redirects to the correct endpoint
=> fix(Middleware): Check settings for callback URL

docs/installation.rst
* Add missing `csrf_token` / `csrf_input`
* Shorten snippets by removing `html`/`body` tags 
* Fix Jinja2 example
=> Tweak logout template examples

docs/settings.rst, mozilla_django_oidc/auth.py, tests/test_auth.py
**Timeout**
Currently all requests to the OpenID Connect provider have no timeout set in the python `requests` GET and POST requests (3 in total). This means if the OIDC Provider is very slow or not reachable, the `mozilla-django-oidc` library will hang indefinitely.
With this merge request you can now define the `OIDC_TIMEOUT` value. Default value is `None` to be backwards compatible with the current situation.
Example:
```
OIDC_TIMEOUT = 10
```
**Proxy**
In case the OIDC Provider can only be reached via a proxy server from the library, the proxy can now be defined with the `OIDC_PROXY` settings variable. The default value is also `None` to be backwards compatible.
Example:
```
OIDC_PROXY = {
'https': 'http://proxy.example.org:8000',
}
=> Added configuration options to define a timeout and a proxy

docs/installation.rst
The previous set of docs were constructing `urlpatterns` in Django 1.x style; this changes the docs to reflect docs for Django 2 and above.
=> Update urls install config for Django 2.0+

HISTORY.rst, mozilla_django_oidc/auth.py, tests/test_auth.py
Prior to this change, when a JWKS was delivered with multiple JWK with the same `kid` but different `alg` specified, the `retrieve_matching_jwk` function would only consider the first key in the list where the `kid` matched.  If the `alg` didn't match, an exception would be raised and if there was a valid JWK with the right `alg` (eg later in the list) it would not be considered.
In the JWK spec (https://tools.ietf.org/html/rfc7517#section-4.4), the `alg` value isn't required to be unique -- only to match -- so the check shouldn't raise an exception at this point, but rather continue checking all remaining JWKs.
With this change, an exception is still raised at the end if no valid JWK is found.  Test output was updated and a new test added to ensure the right key is retrieved from a list …
=> Fix JWKS handling with same `kid` but different `alg` across JWKs

HISTORY.rst, docs/settings.rst, mozilla_django_oidc/middleware.py, tests/test_middleware.py
Support regex patterns in ``OIDC_EXEMPT_URLS``, to avoid session renewal for any request path that matches the pattern.
This was discussed as an alternate implementation in PR #310, which was a solution for follow-on work for https://github.com/mozilla-services/socorro/pull/4957. This would be used there as:
```
OIDC_EXEMPT_URLS = [
"supersearch:search_fields",  # data-fields-url
"supersearch:search_results",  # data-results-url
"/buginfo/bug",
"signature:signature_summary",  # data-urls-summary
"signature:signature_reports",  # data-urls-reports
"signature:signature_bugzilla",  # data-urls-bugzilla
"signature:signature_comments",  # data-urls-comments
"signature:signature_correlations",  # data-urls-correlations
re.compile(r"^/signature/graphs/?P<field>\w+)/$"),  # data-urls-graphs …
```
=> Add regex patterns to OIDC_EXEMPT_URLS setting

docs/drf.rst
DRF will not authenticate properly if SessionAuthentication is not added.
See #328, #265, and [StackOverflow question](https://stackoverflow.com/questions/35601130/django-rest-framework-using-tokenauthentication-with-browsable-api)
=> Add SessionAuthentication to DRF auth classes

mozilla_django_oidc/middleware.py, tests/test_middleware.py
As discussed over on #369 - I've made the middleware class settings discovery to be done in the `__init__` method similarly to `OIDCAuthenticationBackend`
Also updated the overridden settings on the middleware test because the are required for anything accessing the middleware now
=> #369: Update middleware init to configure settings

mozilla_django_oidc/auth.py
Section 4.5 of RFC 7517 states: "Use of [kid] is OPTIONAL".
The current code assumes that `kid` is always provided.
This is not always the case, for example the OIDC implementation of
SATOSA does not provide `kid`.
This case should be handled gracefully instead of causing a
`KeyErrror`.
Fixes: #375
=> Do not fail if JWK doesn't include key id

tests/test_auth.py, tests/test_contrib_drf.py, tests/test_utils.py, tests/test_views.py
Comporisons with None should always use the identity operator, not the
equality operator
=> tests: Check for None with assertIsNone

mozilla_django_oidc/middleware.py
* urllib.parse.urlencode quotes strings using `quote_plus`
* this patch uses urllib.parse.quote instead for compatibility with some providers
=> Fix url encoding using escaped space characters

docs/installation.rst
The method `filter_users_by_claim()` should return an object that supports `len()`. The previous example in the documentation returned the user object directly. Wrapping the user in a list fixes the issue.
This is not an issues with the actual code. This PR fixes the example on how to override the user matching in the documentation.
=> Users filter in docs should return collection

mozilla_django_oidc/views.py
LOGIN_REDIRECT_URL is a general django setting. According to Django docs, it should accept an URL or named URL pattern (see https://docs.djangoproject.com/en/stable/ref/settings/#login-redirect-url). However, if we use a named URL pattern, mozilla-django-oidc does not work properly.
The solution uses django.shortcuts resolve_url method, which is not publish API as far as I know. However, it is available at least in Django 2.2 to 4.x.
=> LOGIN_REDIRECT_URL should accept an URL or named URL pattern

mozilla_django_oidc/middleware.py
otherwise refreshing authentication is missing the extra params that the first authentication has (in the View)
=> fix: add missing extra params to SessionRefresh

docs/settings.rst
=> Document OIDC_USERNAME_ALGO

docs/settings.rst, mozilla_django_oidc/views.py, tests/test_views.py
Not all authorization providers yet support PKCE layered on top of the normal, secret-based authorization code flow -- for example, [Mozilla Accounts explicitly forbids it](https://github.com/mozilla/fxa-auth-server/blob/master/fxa-oauth-server/docs/api.md#request-parameters-7) -- so in order to avoid the next release being a potentially breaking change, let's set the default value of `OIDC_USE_PKCE` to `False`.
=> disable PKCE by default
